package MasterUML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_AbstractTip = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Agregacija = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Asocijacija = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_DijagramKlasa = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Klasa = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Kompozicija = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Parametar = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_PredefinisaneVrednosti = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_SpecifikacijaAtributa = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_SpecifikacijaOperacije = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case 0:
        return props_AbstractTip;
      case 1:
        return props_Agregacija;
      case 2:
        return props_Asocijacija;
      case 3:
        return props_DijagramKlasa;
      case 4:
        return props_Klasa;
      case 5:
        return props_Kompozicija;
      case 6:
        return props_Parametar;
      case 7:
        return props_PredefinisaneVrednosti;
      case 8:
        return props_SpecifikacijaAtributa;
      case 9:
        return props_SpecifikacijaOperacije;
    }
    throw new IllegalStateException("Unknown concept " + c);
  }
}
