package MasterUML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_Agregacija = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Asocijacija = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_AsocijacijaReference = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_BidirekcionaAsocijacija = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_DijagramKlasa = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ElementiDijagramaKlasa = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ElementiUMLProfila = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ElementiVeze = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Interfejs = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Klasa = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Kolona = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Kompozicija = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Nasledjivanje = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Ogranicenja = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_PovratnAsocijacija = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Realizacija = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_SpecifikacijaAtributa = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_SpecifikacijaOperacije = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Tabela = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_TipKolone = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_UMLProfilDijagramKlasa = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_UnidirekcionaAsocijacija = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case 0:
        return props_Agregacija;
      case 1:
        return props_Asocijacija;
      case 2:
        return props_AsocijacijaReference;
      case 3:
        return props_BidirekcionaAsocijacija;
      case 4:
        return props_DijagramKlasa;
      case 5:
        return props_ElementiDijagramaKlasa;
      case 6:
        return props_ElementiUMLProfila;
      case 7:
        return props_ElementiVeze;
      case 8:
        return props_Interfejs;
      case 9:
        return props_Klasa;
      case 10:
        return props_Kolona;
      case 11:
        return props_Kompozicija;
      case 12:
        return props_Nasledjivanje;
      case 13:
        return props_Ogranicenja;
      case 14:
        return props_PovratnAsocijacija;
      case 15:
        return props_Realizacija;
      case 16:
        return props_SpecifikacijaAtributa;
      case 17:
        return props_SpecifikacijaOperacije;
      case 18:
        return props_Tabela;
      case 19:
        return props_TipKolone;
      case 20:
        return props_UMLProfilDijagramKlasa;
      case 21:
        return props_UnidirekcionaAsocijacija;
    }
    throw new IllegalStateException("Unknown concept " + c);
  }
}
