package MasterUML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum EnumKardinalnosti {
  _0____("[0..*]", "0..*"),
  _1____("[1..*]", "1..*"),
  _0__1_("[0..1]", "0..1"),
  _1__1_("[1..1]", "1..1");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private EnumKardinalnosti(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<EnumKardinalnosti> getConstants() {
    List<EnumKardinalnosti> list = ListSequence.fromList(new LinkedList<EnumKardinalnosti>());
    ListSequence.fromList(list).addElement(EnumKardinalnosti._0____);
    ListSequence.fromList(list).addElement(EnumKardinalnosti._1____);
    ListSequence.fromList(list).addElement(EnumKardinalnosti._0__1_);
    ListSequence.fromList(list).addElement(EnumKardinalnosti._1__1_);
    return list;
  }
  public static EnumKardinalnosti getDefault() {
    return EnumKardinalnosti._0____;
  }
  public static EnumKardinalnosti parseValue(String value) {
    if (value == null) {
      return EnumKardinalnosti.getDefault();
    }
    if (value.equals(EnumKardinalnosti._0____.getValueAsString())) {
      return EnumKardinalnosti._0____;
    }
    if (value.equals(EnumKardinalnosti._1____.getValueAsString())) {
      return EnumKardinalnosti._1____;
    }
    if (value.equals(EnumKardinalnosti._0__1_.getValueAsString())) {
      return EnumKardinalnosti._0__1_;
    }
    if (value.equals(EnumKardinalnosti._1__1_.getValueAsString())) {
      return EnumKardinalnosti._1__1_;
    }
    return EnumKardinalnosti.getDefault();
  }
}
