package MasterUML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum EnumPredefinisaniTip {
  string("string", "string"),
  boolean_2scwt4_b("boolean", "boolean"),
  int_2scwt4_c("int", "int"),
  double_2scwt4_d("double", "double"),
  date("date", "date"),
  autoinkrement("autoinkrement", "autoincrement");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private EnumPredefinisaniTip(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<EnumPredefinisaniTip> getConstants() {
    List<EnumPredefinisaniTip> list = ListSequence.fromList(new LinkedList<EnumPredefinisaniTip>());
    ListSequence.fromList(list).addElement(EnumPredefinisaniTip.string);
    ListSequence.fromList(list).addElement(EnumPredefinisaniTip.boolean_2scwt4_b);
    ListSequence.fromList(list).addElement(EnumPredefinisaniTip.int_2scwt4_c);
    ListSequence.fromList(list).addElement(EnumPredefinisaniTip.double_2scwt4_d);
    ListSequence.fromList(list).addElement(EnumPredefinisaniTip.date);
    ListSequence.fromList(list).addElement(EnumPredefinisaniTip.autoinkrement);
    return list;
  }
  public static EnumPredefinisaniTip getDefault() {
    return EnumPredefinisaniTip.string;
  }
  public static EnumPredefinisaniTip parseValue(String value) {
    if (value == null) {
      return EnumPredefinisaniTip.getDefault();
    }
    if (value.equals(EnumPredefinisaniTip.string.getValueAsString())) {
      return EnumPredefinisaniTip.string;
    }
    if (value.equals(EnumPredefinisaniTip.boolean_2scwt4_b.getValueAsString())) {
      return EnumPredefinisaniTip.boolean_2scwt4_b;
    }
    if (value.equals(EnumPredefinisaniTip.int_2scwt4_c.getValueAsString())) {
      return EnumPredefinisaniTip.int_2scwt4_c;
    }
    if (value.equals(EnumPredefinisaniTip.double_2scwt4_d.getValueAsString())) {
      return EnumPredefinisaniTip.double_2scwt4_d;
    }
    if (value.equals(EnumPredefinisaniTip.date.getValueAsString())) {
      return EnumPredefinisaniTip.date;
    }
    if (value.equals(EnumPredefinisaniTip.autoinkrement.getValueAsString())) {
      return EnumPredefinisaniTip.autoinkrement;
    }
    return EnumPredefinisaniTip.getDefault();
  }
}
