package MasterUML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum EnumVidljivost {
  privatni("-", "privatni"),
  javni("+", "javni"),
  zasticeni("#", "zasticeni"),
  paketni("~", "paketni");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private EnumVidljivost(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<EnumVidljivost> getConstants() {
    List<EnumVidljivost> list = ListSequence.fromList(new LinkedList<EnumVidljivost>());
    ListSequence.fromList(list).addElement(EnumVidljivost.privatni);
    ListSequence.fromList(list).addElement(EnumVidljivost.javni);
    ListSequence.fromList(list).addElement(EnumVidljivost.zasticeni);
    ListSequence.fromList(list).addElement(EnumVidljivost.paketni);
    return list;
  }
  public static EnumVidljivost getDefault() {
    return EnumVidljivost.privatni;
  }
  public static EnumVidljivost parseValue(String value) {
    if (value == null) {
      return EnumVidljivost.getDefault();
    }
    if (value.equals(EnumVidljivost.privatni.getValueAsString())) {
      return EnumVidljivost.privatni;
    }
    if (value.equals(EnumVidljivost.javni.getValueAsString())) {
      return EnumVidljivost.javni;
    }
    if (value.equals(EnumVidljivost.zasticeni.getValueAsString())) {
      return EnumVidljivost.zasticeni;
    }
    if (value.equals(EnumVidljivost.paketni.getValueAsString())) {
      return EnumVidljivost.paketni;
    }
    return EnumVidljivost.getDefault();
  }
}
