package MasterUML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum EnumPrimarniKljuc {
  _(" ", " "),
  __PK__("<<PK>>", "PK");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private EnumPrimarniKljuc(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<EnumPrimarniKljuc> getConstants() {
    List<EnumPrimarniKljuc> list = ListSequence.fromList(new LinkedList<EnumPrimarniKljuc>());
    ListSequence.fromList(list).addElement(EnumPrimarniKljuc._);
    ListSequence.fromList(list).addElement(EnumPrimarniKljuc.__PK__);
    return list;
  }
  public static EnumPrimarniKljuc getDefault() {
    return EnumPrimarniKljuc._;
  }
  public static EnumPrimarniKljuc parseValue(String value) {
    if (value == null) {
      return EnumPrimarniKljuc.getDefault();
    }
    if (value.equals(EnumPrimarniKljuc._.getValueAsString())) {
      return EnumPrimarniKljuc._;
    }
    if (value.equals(EnumPrimarniKljuc.__PK__.getValueAsString())) {
      return EnumPrimarniKljuc.__PK__;
    }
    return EnumPrimarniKljuc.getDefault();
  }
}
