package MasterUML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum EnumPredefinisaniTip {
  String("String", "String"),
  Boolean("Boolean", "Boolean"),
  Integer("Integer", "Integer"),
  Double("Double", "Double"),
  Date("Date", "Date");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private EnumPredefinisaniTip(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<EnumPredefinisaniTip> getConstants() {
    List<EnumPredefinisaniTip> list = ListSequence.fromList(new LinkedList<EnumPredefinisaniTip>());
    ListSequence.fromList(list).addElement(EnumPredefinisaniTip.String);
    ListSequence.fromList(list).addElement(EnumPredefinisaniTip.Boolean);
    ListSequence.fromList(list).addElement(EnumPredefinisaniTip.Integer);
    ListSequence.fromList(list).addElement(EnumPredefinisaniTip.Double);
    ListSequence.fromList(list).addElement(EnumPredefinisaniTip.Date);
    return list;
  }
  public static EnumPredefinisaniTip getDefault() {
    return EnumPredefinisaniTip.String;
  }
  public static EnumPredefinisaniTip parseValue(String value) {
    if (value == null) {
      return EnumPredefinisaniTip.getDefault();
    }
    if (value.equals(EnumPredefinisaniTip.String.getValueAsString())) {
      return EnumPredefinisaniTip.String;
    }
    if (value.equals(EnumPredefinisaniTip.Boolean.getValueAsString())) {
      return EnumPredefinisaniTip.Boolean;
    }
    if (value.equals(EnumPredefinisaniTip.Integer.getValueAsString())) {
      return EnumPredefinisaniTip.Integer;
    }
    if (value.equals(EnumPredefinisaniTip.Double.getValueAsString())) {
      return EnumPredefinisaniTip.Double;
    }
    if (value.equals(EnumPredefinisaniTip.Date.getValueAsString())) {
      return EnumPredefinisaniTip.Date;
    }
    return EnumPredefinisaniTip.getDefault();
  }
}
