package MasterUML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum EnumTipKolone {
  VARCHAR_255_("VARCHAR(255)", "varchar"),
  BOOLEAN("BOOLEAN", "boolean"),
  INTEGER("INTEGER", "int"),
  DOUBLE("DOUBLE", "double"),
  DATE("DATE", "date"),
  AUTOINCREMENT("AUTOINCREMENT", "autoincrement");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private EnumTipKolone(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<EnumTipKolone> getConstants() {
    List<EnumTipKolone> list = ListSequence.fromList(new LinkedList<EnumTipKolone>());
    ListSequence.fromList(list).addElement(EnumTipKolone.VARCHAR_255_);
    ListSequence.fromList(list).addElement(EnumTipKolone.BOOLEAN);
    ListSequence.fromList(list).addElement(EnumTipKolone.INTEGER);
    ListSequence.fromList(list).addElement(EnumTipKolone.DOUBLE);
    ListSequence.fromList(list).addElement(EnumTipKolone.DATE);
    ListSequence.fromList(list).addElement(EnumTipKolone.AUTOINCREMENT);
    return list;
  }
  public static EnumTipKolone getDefault() {
    return EnumTipKolone.BOOLEAN;
  }
  public static EnumTipKolone parseValue(String value) {
    if (value == null) {
      return EnumTipKolone.getDefault();
    }
    if (value.equals(EnumTipKolone.VARCHAR_255_.getValueAsString())) {
      return EnumTipKolone.VARCHAR_255_;
    }
    if (value.equals(EnumTipKolone.BOOLEAN.getValueAsString())) {
      return EnumTipKolone.BOOLEAN;
    }
    if (value.equals(EnumTipKolone.INTEGER.getValueAsString())) {
      return EnumTipKolone.INTEGER;
    }
    if (value.equals(EnumTipKolone.DOUBLE.getValueAsString())) {
      return EnumTipKolone.DOUBLE;
    }
    if (value.equals(EnumTipKolone.DATE.getValueAsString())) {
      return EnumTipKolone.DATE;
    }
    if (value.equals(EnumTipKolone.AUTOINCREMENT.getValueAsString())) {
      return EnumTipKolone.AUTOINCREMENT;
    }
    return EnumTipKolone.getDefault();
  }
}
