package ProsirenjeDijagramaKlasa.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import java.util.Map;
import java.util.HashMap;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      Integer preIndex = indices_xbvbvu_a0a.get(cncpt);
      int switchIndex = (preIndex == null ? -1 : preIndex);
      switch (switchIndex) {
        case 0:
          if (true) {
            return Collections.<ConceptEditor>singletonList(new Kolona_Editor());
          }
          break;
        case 1:
          if (true) {
            return Collections.<ConceptEditor>singletonList(new OgranicenjaPrimarniKljuc_Editor());
          }
          break;
        case 2:
          if (true) {
            return Collections.<ConceptEditor>singletonList(new OgranicenjaSpoljniKljuc_Editor());
          }
          break;
        case 3:
          if (true) {
            return Collections.<ConceptEditor>singletonList(new Tabela_Editor());
          }
          break;
        case 4:
          if (true) {
            return Collections.<ConceptEditor>singletonList(new UMLProfilDijagramKlasa_Editor());
          }
          break;
        default:
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static Map<SAbstractConcept, Integer> buildConceptIndices(SAbstractConcept... concepts) {
    HashMap<SAbstractConcept, Integer> res = new HashMap<SAbstractConcept, Integer>();
    int counter = 0;
    for (SAbstractConcept c : concepts) {
      res.put(c, counter++);
    }
    return res;
  }
  private static final Map<SAbstractConcept, Integer> indices_xbvbvu_a0a = buildConceptIndices(MetaAdapterFactory.getConcept(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b4cL, "ProsirenjeDijagramaKlasa.structure.Kolona"), MetaAdapterFactory.getConcept(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x1b60372de7c97345L, "ProsirenjeDijagramaKlasa.structure.OgranicenjaPrimarniKljuc"), MetaAdapterFactory.getConcept(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x1b60372de80e12caL, "ProsirenjeDijagramaKlasa.structure.OgranicenjaSpoljniKljuc"), MetaAdapterFactory.getConcept(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, "ProsirenjeDijagramaKlasa.structure.Tabela"), MetaAdapterFactory.getConcept(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9dbe397L, "ProsirenjeDijagramaKlasa.structure.UMLProfilDijagramKlasa"));
}
