package ProsirenjeDijagramaKlasa.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_ElementiUMLProfila = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Kolona = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Ogranicenja = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_OgranicenjaPrimarniKljuc = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_OgranicenjaSpoljniKljuc = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Tabela = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_UMLProfilDijagramKlasa = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case 0:
        return props_ElementiUMLProfila;
      case 1:
        return props_Kolona;
      case 2:
        return props_Ogranicenja;
      case 3:
        return props_OgranicenjaPrimarniKljuc;
      case 4:
        return props_OgranicenjaSpoljniKljuc;
      case 5:
        return props_Tabela;
      case 6:
        return props_UMLProfilDijagramKlasa;
    }
    throw new IllegalStateException("Unknown concept " + c);
  }
}
