package ProsirenjeDijagramaKlasa.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum EnumOstalaOgranicenja {
  NOT_NULL("NOT NULL", "NOT NULL"),
  _(" ", null);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private EnumOstalaOgranicenja(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<EnumOstalaOgranicenja> getConstants() {
    List<EnumOstalaOgranicenja> list = ListSequence.fromList(new LinkedList<EnumOstalaOgranicenja>());
    ListSequence.fromList(list).addElement(EnumOstalaOgranicenja.NOT_NULL);
    ListSequence.fromList(list).addElement(EnumOstalaOgranicenja._);
    return list;
  }
  public static EnumOstalaOgranicenja getDefault() {
    return EnumOstalaOgranicenja._;
  }
  public static EnumOstalaOgranicenja parseValue(String value) {
    if (value == null) {
      return EnumOstalaOgranicenja.getDefault();
    }
    if (value.equals(EnumOstalaOgranicenja.NOT_NULL.getValueAsString())) {
      return EnumOstalaOgranicenja.NOT_NULL;
    }
    if (value.equals(EnumOstalaOgranicenja._.getValueAsString())) {
      return EnumOstalaOgranicenja._;
    }
    return EnumOstalaOgranicenja.getDefault();
  }
}
