package ProsirenjeDijagramaKlasa.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionDescriptorBase;
import jetbrains.mps.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.intentions.IntentionExecutable;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.intentions.IntentionType;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.IntentionExecutableBase;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import java.util.List;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.intentions.IntentionDescriptor;

public final class OgranicenjePK_Intention extends IntentionDescriptorBase implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;
  public OgranicenjePK_Intention() {
    super(MetaAdapterFactory.getConcept(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, "ProsirenjeDijagramaKlasa.structure.Tabela"), IntentionType.NORMAL, false, new SNodePointer("r:5ab12537-c82a-406b-853e-4ff465f1208a(ProsirenjeDijagramaKlasa.intentions)", "1972637307090135663"));
  }
  @Override
  public String getPresentation() {
    return "OgranicenjePK";
  }
  @Override
  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }
  @Override
  public boolean isSurroundWith() {
    return false;
  }
  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new OgranicenjePK_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends IntentionExecutableBase {
    public IntentionImplementation() {
    }
    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Definisi ogranicenje PK";
    }
    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      SNode profil = (SNode) SNodeOperations.getContainingRoot(node);
      List<SNode> ogPKlist = new ArrayList<SNode>();
      List<SNode> kolPrimarniKljuc = new ArrayList<SNode>();
      for (SNode kol : ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x4ec45abfc9ea5b4fL, "kolone"))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SPropertyOperations.hasValue(it, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b4cL, 0x3ecc66e9a27f5f6eL, "primarniKljuc"), "PK", " ");
        }
      })) {
        ListSequence.fromList(kolPrimarniKljuc).addElement(kol);
        SNode ogranPK = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x1b60372de7c97345L, "ProsirenjeDijagramaKlasa.structure.OgranicenjaPrimarniKljuc"));
        SPropertyOperations.set(ogranPK, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x25b8dd4a0db7811aL, 0x142d3f2de722424L, "naziv"), SPropertyOperations.getString(kol, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
        SLinkOperations.setTarget(ogranPK, MetaAdapterFactory.getReferenceLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x25b8dd4a0db7811aL, 0x142d3f2ddd8b49cL, "referenca"), node);
        ListSequence.fromList(ogPKlist).addElement(ogranPK);

      }
      for (SNode asoc : ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(profil, MetaAdapterFactory.getReferenceLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9dbe397L, 0x4ec45abfc9fc90f6L, "dijKlasa")), MetaAdapterFactory.getContainmentLink(0x95e80464dc8c4520L, 0xad10bc8df94efd78L, 0x7558a0229d99fd9eL, 0x7ed1894e5b00ab89L, "elementiDijagramaKlasa"))).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, MetaAdapterFactory.getConcept(0x95e80464dc8c4520L, 0xad10bc8df94efd78L, 0x7e0ff169347d17a4L, "MasterUML.structure.Asocijacija"));
        }
      })) {
        if (SNodeOperations.isInstanceOf(asoc, MetaAdapterFactory.getConcept(0x95e80464dc8c4520L, 0xad10bc8df94efd78L, 0x7ed1894e5b031301L, "MasterUML.structure.Nasledjivanje"))) {
          SNode asocNasl = (SNode) asoc;
          if (SPropertyOperations.hasValue(node, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), SPropertyOperations.getString(SLinkOperations.getTarget(asocNasl, MetaAdapterFactory.getReferenceLink(0x95e80464dc8c4520L, 0xad10bc8df94efd78L, 0x7e0ff169347d17a4L, 0x7ed1894e5b022dcdL, "kraj")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")))) {
            for (SNode nodeTabela : ListSequence.fromList(SLinkOperations.getChildren(profil, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9dbe397L, 0x3ecc66e9a26011ddL, "elementi"))).where(new IWhereFilter<SNode>() {
              public boolean accept(SNode it) {
                return SNodeOperations.isInstanceOf(it, MetaAdapterFactory.getConcept(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, "ProsirenjeDijagramaKlasa.structure.Tabela"));
              }
            })) {
              SNode tblNasledjivanje = (SNode) nodeTabela;
              if (SPropertyOperations.getString(nodeTabela, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equalsIgnoreCase(SPropertyOperations.getString(SLinkOperations.getTarget(asocNasl, MetaAdapterFactory.getReferenceLink(0x95e80464dc8c4520L, 0xad10bc8df94efd78L, 0x7e0ff169347d17a4L, 0x7ed1894e5b022dbaL, "pocetak")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")))) {
                for (SNode nodeKol : ListSequence.fromList(SLinkOperations.getChildren(tblNasledjivanje, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x4ec45abfc9ea5b4fL, "kolone"))).where(new IWhereFilter<SNode>() {
                  public boolean accept(SNode it) {
                    return SPropertyOperations.hasValue(it, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b4cL, 0x3ecc66e9a27f5f6eL, "primarniKljuc"), "PK", " ");
                  }
                })) {
                  SNode ogranPK = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x1b60372de7c97345L, "ProsirenjeDijagramaKlasa.structure.OgranicenjaPrimarniKljuc"));
                  SPropertyOperations.set(ogranPK, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x25b8dd4a0db7811aL, 0x142d3f2de722424L, "naziv"), SPropertyOperations.getString(nodeKol, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
                  SLinkOperations.setTarget(ogranPK, MetaAdapterFactory.getReferenceLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x25b8dd4a0db7811aL, 0x142d3f2ddd8b49cL, "referenca"), tblNasledjivanje);
                  ListSequence.fromList(ogPKlist).addElement(ogranPK);
                  if (!(ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x4ec45abfc9ea5b4fL, "kolone"))).contains(nodeKol))) {
                    SNode nodePKkolona = SNodeOperations.copyNode(nodeKol);
                    SPropertyOperations.set(nodePKkolona, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b4cL, 0x3ecc66e9a27f5f6eL, "primarniKljuc"), null);
                    ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x4ec45abfc9ea5b4fL, "kolone"))).addElement(nodePKkolona);
                  }
                }
              }
            }

          }
        }
        if (SNodeOperations.isInstanceOf(asoc, MetaAdapterFactory.getConcept(0x95e80464dc8c4520L, 0xad10bc8df94efd78L, 0x7558a0229d99fbe3L, "MasterUML.structure.Kompozicija"))) {
          SNode asocKomp = (SNode) asoc;
          if (SPropertyOperations.hasValue(node, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), SPropertyOperations.getString(SLinkOperations.getTarget(asocKomp, MetaAdapterFactory.getReferenceLink(0x95e80464dc8c4520L, 0xad10bc8df94efd78L, 0x7e0ff169347d17a4L, 0x7ed1894e5b022dcdL, "kraj")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")))) {
            for (SNode nodeTabela : ListSequence.fromList(SLinkOperations.getChildren(profil, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9dbe397L, 0x3ecc66e9a26011ddL, "elementi"))).where(new IWhereFilter<SNode>() {
              public boolean accept(SNode it) {
                return SNodeOperations.isInstanceOf(it, MetaAdapterFactory.getConcept(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, "ProsirenjeDijagramaKlasa.structure.Tabela"));
              }
            })) {
              SNode tblKompozicija = (SNode) nodeTabela;
              if (SPropertyOperations.getString(nodeTabela, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equalsIgnoreCase(SPropertyOperations.getString(SLinkOperations.getTarget(asocKomp, MetaAdapterFactory.getReferenceLink(0x95e80464dc8c4520L, 0xad10bc8df94efd78L, 0x7e0ff169347d17a4L, 0x7ed1894e5b022dbaL, "pocetak")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")))) {
                for (SNode nodeKol : ListSequence.fromList(SLinkOperations.getChildren(tblKompozicija, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x4ec45abfc9ea5b4fL, "kolone"))).where(new IWhereFilter<SNode>() {
                  public boolean accept(SNode it) {
                    return SPropertyOperations.hasValue(it, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b4cL, 0x3ecc66e9a27f5f6eL, "primarniKljuc"), "PK", " ");
                  }
                })) {
                  SNode ogranPK = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x1b60372de7c97345L, "ProsirenjeDijagramaKlasa.structure.OgranicenjaPrimarniKljuc"));
                  SPropertyOperations.set(ogranPK, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x25b8dd4a0db7811aL, 0x142d3f2de722424L, "naziv"), SPropertyOperations.getString(nodeKol, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
                  SLinkOperations.setTarget(ogranPK, MetaAdapterFactory.getReferenceLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x25b8dd4a0db7811aL, 0x142d3f2ddd8b49cL, "referenca"), tblKompozicija);
                  ListSequence.fromList(ogPKlist).addElement(ogranPK);
                  if (!(ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x4ec45abfc9ea5b4fL, "kolone"))).contains(nodeKol))) {
                    SNode nodePKkolona = SNodeOperations.copyNode(nodeKol);
                    SPropertyOperations.set(nodePKkolona, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b4cL, 0x3ecc66e9a27f5f6eL, "primarniKljuc"), null);
                    ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x4ec45abfc9ea5b4fL, "kolone"))).addElement(nodePKkolona);
                  }

                }
              }
            }

          }
        }
        if (SNodeOperations.isInstanceOf(asoc, MetaAdapterFactory.getConcept(0x95e80464dc8c4520L, 0xad10bc8df94efd78L, 0x7558a0229d99fbf6L, "MasterUML.structure.Agregacija"))) {
          SNode asocAgreg = (SNode) asoc;
          if (SPropertyOperations.hasValue(node, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), SPropertyOperations.getString(SLinkOperations.getTarget(asocAgreg, MetaAdapterFactory.getReferenceLink(0x95e80464dc8c4520L, 0xad10bc8df94efd78L, 0x7e0ff169347d17a4L, 0x7ed1894e5b022dcdL, "kraj")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")))) {
            for (SNode nodeTabela : ListSequence.fromList(SLinkOperations.getChildren(profil, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9dbe397L, 0x3ecc66e9a26011ddL, "elementi"))).where(new IWhereFilter<SNode>() {
              public boolean accept(SNode it) {
                return SNodeOperations.isInstanceOf(it, MetaAdapterFactory.getConcept(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, "ProsirenjeDijagramaKlasa.structure.Tabela"));
              }
            })) {
              SNode tblAgregacija = (SNode) nodeTabela;
              if (SPropertyOperations.getString(nodeTabela, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equalsIgnoreCase(SPropertyOperations.getString(SLinkOperations.getTarget(asocAgreg, MetaAdapterFactory.getReferenceLink(0x95e80464dc8c4520L, 0xad10bc8df94efd78L, 0x7e0ff169347d17a4L, 0x7ed1894e5b022dbaL, "pocetak")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")))) {
                for (SNode nodeKol : ListSequence.fromList(SLinkOperations.getChildren(tblAgregacija, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x4ec45abfc9ea5b4fL, "kolone"))).where(new IWhereFilter<SNode>() {
                  public boolean accept(SNode it) {
                    return SPropertyOperations.hasValue(it, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b4cL, 0x3ecc66e9a27f5f6eL, "primarniKljuc"), "PK", " ");
                  }
                })) {
                  SNode ogranPK = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x1b60372de7c97345L, "ProsirenjeDijagramaKlasa.structure.OgranicenjaPrimarniKljuc"));
                  SPropertyOperations.set(ogranPK, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x25b8dd4a0db7811aL, 0x142d3f2de722424L, "naziv"), SPropertyOperations.getString(nodeKol, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
                  SLinkOperations.setTarget(ogranPK, MetaAdapterFactory.getReferenceLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x25b8dd4a0db7811aL, 0x142d3f2ddd8b49cL, "referenca"), tblAgregacija);
                  ListSequence.fromList(ogPKlist).addElement(ogranPK);
                  if (!(ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x4ec45abfc9ea5b4fL, "kolone"))).contains(nodeKol))) {
                    SNode nodePKkolona = SNodeOperations.copyNode(nodeKol);
                    SPropertyOperations.set(nodePKkolona, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b4cL, 0x3ecc66e9a27f5f6eL, "primarniKljuc"), null);
                    ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x4ec45abfc9ea5b4fL, "kolone"))).addElement(nodePKkolona);
                  }

                }
              }
            }

          }
        }
        if (SNodeOperations.isInstanceOf(asoc, MetaAdapterFactory.getConcept(0x95e80464dc8c4520L, 0xad10bc8df94efd78L, 0x32a15a2c26b0fb09L, "MasterUML.structure.AsocijativnaKlasa"))) {
          SNode asocAsKl = (SNode) asoc;
          if (SPropertyOperations.hasValue(node, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), SPropertyOperations.getString(SLinkOperations.getTarget(asocAsKl, MetaAdapterFactory.getReferenceLink(0x95e80464dc8c4520L, 0xad10bc8df94efd78L, 0x32a15a2c26b0fb09L, 0x1b60372de7f796e5L, "asocijativnaKlasa")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")))) {
            for (SNode nodeTabela : ListSequence.fromList(SLinkOperations.getChildren(profil, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9dbe397L, 0x3ecc66e9a26011ddL, "elementi"))).where(new IWhereFilter<SNode>() {
              public boolean accept(SNode it) {
                return SNodeOperations.isInstanceOf(it, MetaAdapterFactory.getConcept(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, "ProsirenjeDijagramaKlasa.structure.Tabela"));
              }
            })) {
              SNode tblAsocKlasa = (SNode) nodeTabela;
              if (SPropertyOperations.getString(nodeTabela, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equalsIgnoreCase(SPropertyOperations.getString(SLinkOperations.getTarget(asocAsKl, MetaAdapterFactory.getReferenceLink(0x95e80464dc8c4520L, 0xad10bc8df94efd78L, 0x7e0ff169347d17a4L, 0x7ed1894e5b022dbaL, "pocetak")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")))) {
                for (SNode nodeKol : ListSequence.fromList(SLinkOperations.getChildren(tblAsocKlasa, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x4ec45abfc9ea5b4fL, "kolone"))).where(new IWhereFilter<SNode>() {
                  public boolean accept(SNode it) {
                    return SPropertyOperations.hasValue(it, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b4cL, 0x3ecc66e9a27f5f6eL, "primarniKljuc"), "PK", " ");
                  }
                })) {
                  SNode ogranPK = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x1b60372de7c97345L, "ProsirenjeDijagramaKlasa.structure.OgranicenjaPrimarniKljuc"));
                  SPropertyOperations.set(ogranPK, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x25b8dd4a0db7811aL, 0x142d3f2de722424L, "naziv"), SPropertyOperations.getString(nodeKol, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
                  SLinkOperations.setTarget(ogranPK, MetaAdapterFactory.getReferenceLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x25b8dd4a0db7811aL, 0x142d3f2ddd8b49cL, "referenca"), tblAsocKlasa);
                  ListSequence.fromList(ogPKlist).addElement(ogranPK);
                  if (!(ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x4ec45abfc9ea5b4fL, "kolone"))).contains(nodeKol))) {
                    SNode nodePKkolona = SNodeOperations.copyNode(nodeKol);
                    SPropertyOperations.set(nodePKkolona, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b4cL, 0x3ecc66e9a27f5f6eL, "primarniKljuc"), null);
                    ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x4ec45abfc9ea5b4fL, "kolone"))).addElement(nodePKkolona);
                  }

                }
              }
              if (SPropertyOperations.getString(nodeTabela, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equalsIgnoreCase(SPropertyOperations.getString(SLinkOperations.getTarget(asocAsKl, MetaAdapterFactory.getReferenceLink(0x95e80464dc8c4520L, 0xad10bc8df94efd78L, 0x7e0ff169347d17a4L, 0x7ed1894e5b022dcdL, "kraj")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")))) {
                for (SNode nodeKol : ListSequence.fromList(SLinkOperations.getChildren(tblAsocKlasa, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x4ec45abfc9ea5b4fL, "kolone"))).where(new IWhereFilter<SNode>() {
                  public boolean accept(SNode it) {
                    return SPropertyOperations.hasValue(it, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b4cL, 0x3ecc66e9a27f5f6eL, "primarniKljuc"), "PK", " ");
                  }
                })) {
                  SNode ogranPK = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x1b60372de7c97345L, "ProsirenjeDijagramaKlasa.structure.OgranicenjaPrimarniKljuc"));
                  SPropertyOperations.set(ogranPK, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x25b8dd4a0db7811aL, 0x142d3f2de722424L, "naziv"), SPropertyOperations.getString(nodeKol, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
                  SLinkOperations.setTarget(ogranPK, MetaAdapterFactory.getReferenceLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x25b8dd4a0db7811aL, 0x142d3f2ddd8b49cL, "referenca"), tblAsocKlasa);
                  ListSequence.fromList(ogPKlist).addElement(ogranPK);
                  if (!(ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x4ec45abfc9ea5b4fL, "kolone"))).contains(nodeKol))) {
                    SNode nodePKkolona = SNodeOperations.copyNode(nodeKol);
                    SPropertyOperations.set(nodePKkolona, MetaAdapterFactory.getProperty(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b4cL, 0x3ecc66e9a27f5f6eL, "primarniKljuc"), null);
                    ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x4ec45abfc9ea5b4fL, "kolone"))).addElement(nodePKkolona);
                  }

                }

              }

            }

          }
        }

      }
      ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xb3d58ef49e3d4de2L, 0xb3bfe70ac74854dfL, 0x4ec45abfc9ea5b49L, 0x1b60372de7d06bf9L, "ogranicenjaPK"))).addSequence(ListSequence.fromList(ogPKlist));

    }
    @Override
    public IntentionDescriptor getDescriptor() {
      return OgranicenjePK_Intention.this;
    }
  }
}
