package MasterUML.sandbox;

/*Generated by MPS */


public class map_DijagramKlasa {
  public static void main(String[] args) {
    StringBuilder str = new StringBuilder();
    str.append("CREATE TABLE");
    System.out.println(str);
    str.append("stagod");
    map_RelacioniModel.???();
    System.out.println(str);
  }

}
